Repository HETIC-MT-P2021/PROJECT_FINAL_GROUP03, pull requests merged in 2021-11, with the labels that each got.

#40 Fix: updated bot logic.
  bot/commands/birthday_command.go
  bot/connectors/discord_api_connector.go
  bot/connectors/domain_api_connector.go
  bot/enum/routes_enum.go
  bot/handlers/message_handler.go
  bot/helpers/api_request_helper.go
  domainApi/controllers/birthdays.go
  domainApi/controllers/servers.go
  domainApi/router/routes.go
  domainApi/router/run.go
Labels: enhancement

#42 Feat welcome message
  bot/commands/birthday_command.go
  bot/commands/generic_command.go
  bot/commands/welcome_command.go
  bot/handlers/message_handler.go
  bot/helpers/api_request_helper.go
  bot/helpers/helpers.go
  bot/models/welcome-message.go
  env/bot/.env.dist
Labels: enhancement, epic

#45 Feat: birthday message front
  bot/interfaces/discord_interface.go
  domainApi/controllers/servers.go
  domainApi/discordApi/checkForbiddenWords.go
  front/src/components/forms/birthdayMessageForm.css
  front/src/components/forms/birthdayMessageForm.tsx
  front/src/interfaces/server.ts
  front/src/views/server/Server.tsx
  front/yarn.lock
  frontApi/controllers/servers.go
  frontApi/enum/routes_enum.go
  frontApi/models/birthday_message.go
  frontApi/models/forbiddenWordsList.go
  frontApi/models/server.go
  frontApi/router/run.go
  frontApi/services/domainApi.go
Labels: enhancement

#49 Login & Help commands
  README.md
  bot/cmd/generic_command.go
  bot/cmd/help_command.go
  bot/cmd/login_command.go
  bot/go.mod
  bot/go.sum
  env/bot/.env.dist
Labels: documentation, enhancement
